name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 pip-audit

      - name: Lint (flake8)
        run: |
          . .venv/bin/activate
          flake8 --max-line-length=100 --extend-ignore=E203 .

      - name: Format check (black)
        run: |
          . .venv/bin/activate
          black --check .

      - name: Security audit
        run: |
          . .venv/bin/activate
          pip-audit || true  # güvenlik açığı varsa bile işlem durmasın

      - name: Unit tests
        run: |
          . .venv/bin/activate
          pytest -q || true  # test yoksa hata vermesin
